---
title: "snow_surveys"
author: "Erika Lee"
date: "2024-05-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

2023-24 Snow Survey Processing

```{r}
#packages
library(tidyverse)
library(lubridate)
library(plotly)
library(ggplot2)
library(stringr)
library(readxl)
library(rstatix)
library(sf)
library(terra)

setwd("/Volumes/wcnr-network/Research/Kampf/Private/field_data")
```

```{r}
## Plot size
PlotWidth = 16.5
PlotHeight = 9
```

```{r}
## read in geode data - this will be the same every survey
geode_all <- read_excel("nsf/nsf_snow_transects/nsf_geode_snowtransect_points.xlsx") %>%
  mutate(point_name = name) %>%
  select(point_name, everything()) %>%
  select(-c(name, notes))
```

Creating a spatial dataset - \*\* need to work on this part still!

```{r}
#converting geode points to spatial object
geode_sf <- geode_all %>%
  st_as_sf(coords = c("long", "lat"), crs = 4326)

# Create a blank raster template
ext <- st_bbox(geode_sf)
res <- 100 # resolution of the raster
rast <- rast(xmin = ext["xmin"], xmax = ext["xmax"], ymin = ext["ymin"], ymax = ext["ymax"], 
             resolution = res, crs = st_crs(geode_sf)$wkt)

# Interpolate the elevation data
#gps_raster <- rasterize(geode_sf, rast, field = "elev_m", fun = mean)

#Calculate the aspect using the terrain function from the terra package
#aspect_raster <- terrain(gps_raster, v = "aspect", unit = "degrees")

#extract aspect for each point
#geode_sf$aspect <- extract(aspect_raster, geode_sf)

#convert back to a dataframe for further data manipulation
geode_final <- geode_sf %>%
  st_drop_geometry() %>%
  as.data.frame()
```

### Monthly Data - Transitional Burned/Unburned

```{r}
#read in burned data and seperate into depths and pit measurements
trans_b_depth <- read_excel("nsf/nsf_snow_transects/trans_b_ab.xlsx") %>%
  select(1:7) %>%
  mutate(date = ymd(date, tz = 'MST'))

## average across for depths by point id
trans_b_depths_avg <- trans_b_depth %>%
  rowwise() %>%
  mutate(avg_depth_cm = mean(c(depth_1_cm,
                               depth_2_cm,
                               depth_3_cm,
                               depth_4_cm,
                               depth_5_cm),
                             na.rm=T)) %>%
  select(-c(3:7))

trans_b_swe <- read_excel("nsf/nsf_snow_transects/trans_b_ab.xlsx", sheet = "swe") %>%
  mutate(date = ymd(date, tz = 'MST'))
#this is wedge and swe tube combined
#still need to get time column to be accurate without a weird date

#average swe for both swe tube and wedges
trans_b_swe_avg <- trans_b_swe %>%
  rowwise() %>%
  mutate(avg_depth_cm = mean(c(depth1_cm,
                               depth2_cm,
                               depth3_cm,
                               depth4_cm,
                               depth5_cm),
                             na.rm=T)) %>%
  mutate(avg_dens_tube = mean(c(density1_gcm3, density2_gcm3, density3_gcm3))) %>%
  mutate(avg_swe_tube = mean(c(swe1_cm...13, swe2_cm...18, swe3_cm...23))) %>%
  mutate(avg_dens_wedge = mean(c(wedge1_density_gcm3, wedge2_density_gcm3, wedge3_density_gcm3, wedge4_density_gcm3, wedge5_density_gcm3, wedge6_density_gcm3, wedge7_density_gcm3))) %>%
  mutate(avg_swe_wedge = mean(c(swe1_cm...30, swe2_cm...36, swe3_cm...42, swe3_cm...42, swe5_cm, swe6_cm, swe7_cm))) %>%
  #selecting just the averages
    select(1:3, avg_depth_cm, avg_dens_tube, avg_swe_tube, avg_dens_wedge, avg_swe_wedge)
  
#get rid of stuff we don't care about right now
all_trans_b_sum <- trans_b_swe_avg %>%
  select(point_name, date, avg_depth_cm, avg_dens_tube, avg_swe_tube, avg_dens_wedge, avg_swe_wedge)

trans_b_temp <- read_excel("nsf/nsf_snow_transects/trans_b_ab.xlsx", sheet = "temp") %>%
  mutate(date = ymd(date, tz = 'MST'))
```

```{r}
#read in ub data and seperate into depths and pit measurements
trans_ub_depth <- read_excel("nsf/nsf_snow_transects/trans_ub_ag.xlsx") %>%
  select(1:7) %>%
  mutate(date = ymd(date, tz = 'MST'))

## average across for depths by point id
trans_ub_depths_avg <- trans_ub_depth %>%
  rowwise() %>%
  mutate(avg_depth_cm = mean(c(depth_1_cm,
                               depth_2_cm,
                               depth_3_cm,
                               depth_4_cm,
                               depth_5_cm),
                             na.rm=T)) %>%
  select(-c(3:7))

trans_ub_swe <- read_excel("nsf/nsf_snow_transects/trans_ub_ag.xlsx", sheet = "swe") %>%
  mutate(date = ymd(date, tz = 'MST'))
#this is wedge and swe tube combined
#still need to get time column to be accurate without a weird date

#average swe for both swe tube and wedges
trans_ub_swe_avg <- trans_ub_swe %>%
  rowwise() %>%
  mutate(avg_depth_cm = mean(c(depth1_cm,
                               depth2_cm, depth3_cm,
                               depth4_cm,
                               depth5_cm),
                             na.rm=T)) %>%
  mutate(avg_dens_tube = mean(c(density1_gcm3, density2_gcm3, density3_gcm3))) %>%
  mutate(avg_swe_tube = mean(c(swe1_cm...13, swe2_cm...18, swe3_cm...23))) %>%
  mutate(avg_dens_wedge = mean(c(wedge1_density_gcm3, wedge2_density_gcm3, wedge3_density_gcm3, wedge4_density_gcm3, wedge5_density_gcm3, wedge6_density_gcm3))) %>%
  mutate(avg_swe_wedge = mean(c(swe1_cm...30, swe2_cm...36, swe3_cm...42, swe3_cm...42, swe5_cm, swe6_cm))) %>%
  #selecting just the averages
  select(1:3, avg_depth_cm, avg_dens_tube, avg_swe_tube, avg_dens_wedge, avg_swe_wedge)
  
#get rid of stuff we don't care about right now
all_trans_ub_sum <- trans_ub_swe_avg %>%
  select(point_name, date, avg_depth_cm, avg_dens_tube, avg_swe_tube, avg_dens_wedge, avg_swe_wedge)

trans_ub_temp <- read_excel("nsf/nsf_snow_transects/trans_ub_ag.xlsx", sheet = "temp") %>%
  mutate(date = ymd(date, tz = 'MST'))
```

```{r}
#joining trans_b and trans_ub dataframes
all_trans_depths <- trans_b_depth %>%
  full_join(trans_ub_depth) %>%
  #adding a burn column with burn status
  mutate(burn = case_when(
    str_detect(point_name, fixed("ag", ignore_case = TRUE)) ~ "unburned",
    str_detect(point_name, fixed("ab", ignore_case = TRUE)) ~ "burned",
    TRUE ~ NA_character_  # Add a default value if needed
  )) %>%
  select(point_name, date, burn, everything())

avg_all_trans_depths <- trans_b_depths_avg %>%
  full_join(trans_ub_depths_avg) %>%
    mutate(burn = case_when(
    str_detect(point_name, fixed("ag", ignore_case = TRUE)) ~ "unburned",
    str_detect(point_name, fixed("ab", ignore_case = TRUE)) ~ "burned",
    TRUE ~ NA_character_  # Add a default value if needed
  )) %>%
  select(point_name, date, burn, everything())

all_trans_swe <- trans_b_swe %>%
  full_join(trans_ub_swe) %>%
  mutate(burn = case_when(
  str_detect(point_name, fixed("ag", ignore_case = TRUE)) ~ "unburned",
  str_detect(point_name, fixed("ab", ignore_case = TRUE)) ~ "burned",
  TRUE ~ NA_character_  # Add a default value if needed
  )) %>%
  select(point_name, date, burn, everything())

avg_all_trans_swe <- trans_b_swe_avg %>%
  full_join(trans_ub_swe_avg) %>%
    mutate(burn = case_when(
    str_detect(point_name, fixed("ag", ignore_case = TRUE)) ~ "unburned",
    str_detect(point_name, fixed("ab", ignore_case = TRUE)) ~ "burned",
    TRUE ~ NA_character_  # Add a default value if needed
  )) %>%
  select(point_name, date, burn, everything())

all_trans_temps <- trans_b_temp %>%
  full_join(trans_ub_temp) %>%
    mutate(burn = case_when(
    str_detect(point_name, fixed("ag", ignore_case = TRUE)) ~ "unburned",
    str_detect(point_name, fixed("ab", ignore_case = TRUE)) ~ "burned",
    TRUE ~ NA_character_  # Add a default value if needed
  )) %>%
  select(point_name, date, burn, everything())
```

```{r}
# monthly data for burned and unburned combined
## don't use x and y in this df bc it is NOT from the geode
dec_2023_depth <- all_trans_depths %>%
  filter(date =="2023-12-19")

dec_2023_pit <- all_trans_swe %>%
  filter(date =="2023-12-19") %>%
  select(c(1:14)) 
#no wedge as this measurement was not taken in december
#did not add pit temps to this, as they are in long format

jan_2024_depth <- all_trans_depths %>%
  filter (date =="2024-01-19")

jan_2024_pit <- all_trans_swe %>%
  filter(date == "2024-01-19")

avg_jan_2024_pit <- avg_all_trans_swe %>%
  filter(date == "2024-01-19")

jan_all <- left_join(jan_2024_depth, geode_all, by = "id")

feb_2024_depth <- trans_b_depth %>%
  filter (date =="2024-02-19")

feb_2024_pit <- trans_b_swe %>%
  filter(date == "2024-02-19")

avg_feb_2024_pit <- avg_all_trans_swe %>%
  filter( date =="2024-02-19")

march_2024_depth <- trans_b_depth %>%
  filter (date =="2024-03-20")

march_2024_pit <- trans_b_depth %>%
  filter (date =="2024-03-20")

avg_march_2024_pit <- avg_all_trans_swe %>%
  filter( date =="2024-03-20")

april_2024_depth <- trans_b_depth %>%
  filter (date =="2024-04-19")

april_2024_pit <- trans_b_depth %>%
  filter (date =="2024-04-19")

avg_april_2024_pit <- avg_all_trans_swe %>%
  filter( date =="2024-04-19")
```

### Plots

```{r}
## TRANS - look at variability in depth

plot_all_trans_d <- ggplot(avg_all_trans_depths, aes(x = date)) +
  geom_point(aes(y = avg_depth_cm, color = burn), size = 5) + 
  ggtitle("Transitional") +
  labs(x = "Date", y = "Average Depth (cm)")

# Print the plot
ggplotly(plot_all_trans_d)


## TRANS - looking at variability in swe

# Create the plot with combined geom_point
plot_all_trans_swe <- ggplot(avg_all_trans_swe, aes(x = date)) +
  geom_point(aes(y = avg_swe_tube, color = "avg_swe_tube", shape = point_name), size = 5) +
  geom_point(aes(y = avg_swe_wedge, color = "avg_swe_wedge", shape = point_name), size = 5) +
  ggtitle("Transitional") +
  labs(x = "Date", y = "Average SWE (cm)")

# Print the plot
ggplotly(plot_all_trans_swe)


## trans depth by month facet
PLOT = "depth_monthfacet_trans"
ggplot(all_trans_sum, aes(x=id, y=avg_depth_cm, color=burn, shape=aspect_dir)) +
  geom_point(size=5) +
  ggtitle("transitional") + 
  facet_wrap(~month)

ggsave(paste(PLOT,".png",sep=""), width = PlotWidth, height = PlotHeight)

## trans swe by month facet
PLOT = "swe_monthfacet_trans"
ggplot(all_trans_sum, aes(x=id, y=swe, color=burn, shape=aspect_dir)) +
  geom_point(size=5) +
  ggtitle("transitional") + 
  facet_wrap(~month)

ggsave(paste(PLOT,".png",sep=""), width = PlotWidth, height = PlotHeight)

#boxplots of burned vs unburned by month
PLOT = "trans_depth_boxplot"
ggplot(all_trans_sum, aes(x=as.factor(month), y=avg_depth_cm, fill=burn)) +
  geom_boxplot() + 
  ggtitle("transitional")

ggsave(paste(PLOT,".png",sep=""), width = PlotWidth, height = PlotHeight)

PLOT = "trans_swe_boxplot"
ggplot(all_trans_sum, aes(x=as.factor(month), y=swe, fill=burn)) +
  geom_boxplot() +
  ggtitle("transitional")

ggsave(paste(PLOT,".png",sep=""), width = PlotWidth, height = PlotHeight)

```
